In [1]:
%matplotlib notebook
import requests
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from scipy.signal import savgol_filter
import csv
import geopandas as gpd
import shapely.geometry as sgeo

In [5]:
data20 = pd.read_csv('data/nypd_complaint_2020_geo_cleaned.csv')
data19 = pd.read_csv('data/nypd_complaint_2019_geo_cleaned.csv')

In [10]:
data20_felony = data20[data20['level'] == 'FELONY']
data19_felony = data19[data19['level'] == 'FELONY']

In [14]:
print('felony ratio in 2019: ' + str(len(data19_felony) / len(data19)))
print('felony ratio in 2020: ' + str(len(data20_felony) / len(data20)))

felony ratio in 2019: 0.46009747182455074
felony ratio in 2020: 0.32303489431914456

In [16]:
data2

,Unnamed: 0,Unnamed: 0.1,date,level,susp_age_group,susp_race,susp_sex,vic_age_group,vic_race,vic_sex,latitude,longitude,geometry
0,0,0,12/23/2020,FELONY,UNKNOWN,UNKNOWN,Others,18-24,BLACK,M,40.625769,-73.991417,POINT (-73.99141682199996 40.62576896100006)
1,1,1,12/21/2020,FELONY,UNKNOWN,UNKNOWN,Others,25-44,BLACK,M,40.674583,-73.930222,POINT (-73.93022154099998 40.67458330800008)
2,2,2,11/22/2020,FELONY,UNKNOWN,UNKNOWN,Others,25-44,BLACK,F,40.823101,-73.869690,POINT (-73.86969046099993 40.82310129900002)
3,3,3,11/22/2020,FELONY,25-44,BLACK,M,25-44,BLACK,F,40.887451,-73.847608,POINT (-73.84760778699997 40.88745131300004)
4,4,4,11/21/2020,FELONY,UNKNOWN,UNKNOWN,Others,18-24,BLACK HISPANIC,M,40.800222,-73.930848,POINT (-73.93084834199995 40.80022202900005)
...,...,...,...,...,...,...,...,...,...,...,...,...,...
404846,404846,404887,01/04/2020,MISDEMEANOR,UNKNOWN,WHITE HISPANIC,M,UNKNOWN,UNKNOWN,Others,40.741341,-73.978393,POINT (-73.97839260899997 40.74134137300007)
404847,404847,404888,01/02/2020,FELONY,UNKNOWN,UNKNOWN,Others,45-64,ASIAN / PACIFIC ISLANDER,M,40.688716,-73.826366,POINT (-73.82636559499997 40.68871610400004)
404848,404848,404889,01/02/2020,FELONY,25-44,BLACK,M,UNKNOWN,UNKNOWN,Others,40.789947,-73.975354,POINT (-73.97535415699997 40.78994739900003)
404849,404849,404890,01/05/2020,MISDEMEANOR,45-64,WHITE HISPANIC,M,UNKNOWN,UNKNOWN,Others,40.882338,-73.891652,POINT (-73.89165215599996 40.88233829700005)
404850,404850,404891,01/01/2020,FELONY,25-44,WHITE HISPANIC,F,25-44,WHITE HISPANIC,M,40.749574,-73.873858,POINT (-73.87385847499998 40.74957445600006)